### PR TITLE
updated latest version of qb-garages

### PR DESCRIPTION
**Pull request by dollar-src**
Fixed vehicle properties for qbx
Fixed mod types for qbx

### CODE REVIEW

**Comment by YvanCywan** [comment]
Is this really a fix/push forward in version?
This really just looks like it reverts all changes we have made to the resource.

What does this change? What does this add? How can we merge this without wiping all of our changes in Readme's, and all of the functionality changes we have made to this?

**Review by YvanCywan — CHANGES_REQUESTED** [review]
See above.

**Comment by dollar-src** [comment]
> Is this really a fix/push forward in version? This really just looks like it reverts all changes we have made to the resource.
> 
> What does this change? What does this add? How can we merge this without wiping all of our changes in Readme's, and all of the functionality changes we have made to this?
> 
> I must also stress, there is no reason to be 1:1 with QBCore. This is QBox, not QBCore.

Technically, we can adapt the new version for QBX and improve on it. It looks more elegant and better. I did not encounter any problems when I tested it.

**Comment by YvanCywan** [comment]
> > Is this really a fix/push forward in version? This really just looks like it reverts all changes we have made to the resource.
> > What does this change? What does this add? How can we merge this without wiping all of our changes in Readme's, and all of the functionality changes we have made to this?
> > I must also stress, there is no reason to be 1:1 with QBCore. This is QBox, not QBCore.
> 
> Technically, we can adapt the new version for QBX and improve on it. It looks more elegant and better. I did not encounter any problems when I tested it.

I'm not saying we can't do that, but there are a lot more changes here, this reverts our UI changes, zone changes, etc. It might be worth spending some time isolating what we'd like instead of just wiping the slate clean. Also, elegance is a subjective statement and this change doesn't really look like that it aligns with our mission statement.

**Pull request closed without merging**
